### ISSUE TITLE
clarify licensing

### ISSUE THREAD

**Issue by benbender** [geonativefr/vue3-leaflet#1]
Hey,

love this approach to integrate leaflet and vue3. Would you be able to clarify the license of this code so it can be safely used by others?

Thanks in advance!

**Comment by bpolaszek** [comment]
Hello there! 👋 

We actually open-sourced something we use for our own needs, but as you can see, this repository is very fresh, and we didn't take care of licensing terms yet, and the current code is highly subject to changes before we eventually tag something.

Meanwhile, this repo is public, so current license is "use it at your own risk!" 🙃 
Also don't hesitate if you have any ideas of improvements.
Ben

**Comment by benbender** [comment]
Hey there,

I'm well aware that this package is quite new. I think clearification in an official way would help adoption, but I'm also thinking "your code, your choice!" - so thank you again!

Best,

Benny
